package com.example.greendao1;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.pandachannels.fragmentchinese.fragmentclassify.moble.Students;
import com.example.administrator.pandachannels.fragmentobserve.entity.WenBean;

import com.example.greendao1.StudentsDao;
import com.example.greendao1.WenBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentsDaoConfig;
    private final DaoConfig wenBeanDaoConfig;

    private final StudentsDao studentsDao;
    private final WenBeanDao wenBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        wenBeanDaoConfig = daoConfigMap.get(WenBeanDao.class).clone();
        wenBeanDaoConfig.initIdentityScope(type);

        studentsDao = new StudentsDao(studentsDaoConfig, this);
        wenBeanDao = new WenBeanDao(wenBeanDaoConfig, this);

        registerDao(Students.class, studentsDao);
        registerDao(WenBean.class, wenBeanDao);
    }
    
    public void clear() {
        studentsDaoConfig.clearIdentityScope();
        wenBeanDaoConfig.clearIdentityScope();
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

    public WenBeanDao getWenBeanDao() {
        return wenBeanDao;
    }

}
